export const mapPins = {
  photoLocations: [
    { id: "p1", lat: 25.7617, lng: -80.1918, name: "Wynwood Walls",       description: "Iconic murals, perfect backdrop for car photos", photos: 142, cover: "https://picsum.photos/seed/wynwood1/600/400"   },
    { id: "p2", lat: 25.7827, lng: -80.1300, name: "Design District",     description: "Modern architecture meets chrome",               photos: 89,  cover: "https://picsum.photos/seed/design22/600/400"  },
    { id: "p3", lat: 25.7488, lng: -80.2384, name: "Miracle Mile Strip",  description: "Classic strip for rolling shots",                photos: 67,  cover: "https://picsum.photos/seed/miracle3/600/400"  },
    { id: "p4", lat: 25.7907, lng: -80.1300, name: "Brickell City Centre",description: "Glass towers reflect everything",                photos: 203, cover: "https://picsum.photos/seed/brickell4/600/400" },
    { id: "p5", lat: 25.7743, lng: -80.1937, name: "Overtown Bridge",     description: "Underpass with great lighting at night",         photos: 55,  cover: "https://picsum.photos/seed/overtown5/600/400" },
  ],
  meetupSpots: [
    { id: "m1", lat: 25.8119, lng: -80.1400, name: "Aventura Mall Lot",     description: "North lot, active every Friday night",   regulars: 40 },
    { id: "m2", lat: 25.7356, lng: -80.2625, name: "Bird Road Lot",         description: "Sunday morning classics meetup",          regulars: 25 },
    { id: "m3", lat: 25.7989, lng: -80.2500, name: "Hialeah Speedway Area", description: "Saturday nights, all builds welcome",     regulars: 60 },
    { id: "m4", lat: 25.7650, lng: -80.1340, name: "Bayfront Park",         description: "Waterfront meetup, downtown views",       regulars: 35 },
  ],
  shops: [
    { id: "s1", lat: 25.7980, lng: -80.2620, name: "Miami Motorsport", type: "mod", description: "Full builds, custom fabrication", rating: 4.8, partner: true },
    { id: "s2", lat: 25.7456, lng: -80.2890, name: "South Beach Tires", type: "tires", description: "Performance tires, same day install", rating: 4.6, partner: true },
    { id: "s3", lat: 25.8023, lng: -80.2100, name: "Prestige Detailing", type: "detail", description: "Ceramic coating specialists", rating: 4.9, partner: true },
    { id: "s4", lat: 25.7701, lng: -80.1980, name: "Grove Auto Repair", type: "mechanic", description: "European & JDM specialists", rating: 4.7, partner: false },
    { id: "s5", lat: 25.7612, lng: -80.3700, name: "Kendall Performance", type: "mod", description: "Turbo kits, tune specialists", rating: 4.5, partner: true },
  ],
  scenicRoads: [
    { id: "r1", name: "Rickenbacker Causeway", description: "Bridge to Key Biscayne — sunrise runs", lat: 25.7353, lng: -80.1688 },
    { id: "r2", name: "Old Cutler Road", description: "Canopy of trees, smooth asphalt", lat: 25.6700, lng: -80.2900 },
    { id: "r3", name: "MacArthur Causeway", description: "Miami Beach skyline run", lat: 25.7739, lng: -80.1638 },
  ],
  partners: [
    { id: "b1", lat: 25.7620, lng: -80.1900, name: "Speedway Coffee Co.", type: "coffee", deal: "10% off with Drive 59 app", description: "Car culture coffee shop" },
    { id: "b2", lat: 25.7991, lng: -80.2480, name: "Rev Fuel Station", type: "gas", deal: "3¢/gal off premium fuel", description: "Car guy owned gas station" },
  ],
}

export const events = [
  {
    id: "e1",
    title: "Wynwood Car Meet",
    date: "2026-05-24",
    time: "7:00 PM",
    location: "Wynwood Walls, Miami",
    type: "meetup",
    rsvp: 87,
    max: 150,
    organizer: "MiamiCarScene",
    image: null,
    tags: ["all builds", "photography", "vibes"],
    description: "Monthly Wynwood meet. All cars welcome. Best backdrop in Miami for photos. Photographers will be on site.",
  },
  {
    id: "e2",
    title: "JDM Only — Hialeah",
    date: "2026-05-31",
    time: "6:00 PM",
    location: "Hialeah Speedway Area",
    type: "competition",
    rsvp: 44,
    max: 75,
    organizer: "JDMiami",
    image: null,
    tags: ["JDM", "competition", "prizes"],
    description: "JDM builds only. Top 3 voted by attendees win prizes. Cash prize for best engine bay.",
  },
  {
    id: "e3",
    title: "Sunday Morning Cruise — Old Cutler",
    date: "2026-06-01",
    time: "8:00 AM",
    location: "Bird Road Lot → Old Cutler Road",
    type: "cruise",
    rsvp: 31,
    max: 50,
    organizer: "Drive59Official",
    image: null,
    tags: ["cruise", "scenic", "morning"],
    description: "Meet at Bird Road lot then cruise Old Cutler together. Coffee stop at the end. Keep it clean on the road.",
  },
  {
    id: "e4",
    title: "Exotic & Luxury Showcase",
    date: "2026-06-07",
    time: "5:00 PM",
    location: "Brickell City Centre",
    type: "show",
    rsvp: 120,
    max: 200,
    organizer: "BrickellAutos",
    image: null,
    tags: ["exotic", "luxury", "show", "sponsored"],
    description: "Annual Brickell exotic showcase. Ferraris, Lambos, Rolls Royce welcome. Sponsor booths, free entry for spectators.",
  },
  {
    id: "e5",
    title: "Charity Rally — Miami to Keys",
    date: "2026-06-14",
    time: "9:00 AM",
    location: "Bayfront Park → Key Largo",
    type: "rally",
    rsvp: 28,
    max: 40,
    organizer: "Keys4Kids",
    image: null,
    tags: ["rally", "charity", "fundraiser", "scenic"],
    description: "Fundraiser rally to benefit Miami children's hospital. Scenic route through the Keys. $50 entry goes directly to the cause.",
  },
]

export const clubs = [
  {
    id: "c1",
    name: "305 Exotics",
    members: 48,
    type: "Exotic & Supercar",
    location: "Miami, FL",
    description: "Miami's premier exotic car club. Monthly drives, private events, exclusive dealership tours.",
    public: true,
    fee: "$200/year",
    tags: ["exotic", "supercar", "luxury"],
  },
  {
    id: "c2",
    name: "JDMiami",
    members: 134,
    type: "JDM",
    location: "Miami / Hialeah",
    description: "All JDM builds. Weekly meets in Hialeah. Annual show every October.",
    public: true,
    fee: "Free",
    tags: ["JDM", "honda", "toyota", "nissan", "subaru"],
  },
  {
    id: "c3",
    name: "South Florida Muscle",
    members: 67,
    type: "American Muscle",
    location: "South Florida",
    description: "Mustangs, Camaros, Challengers. Drag days, cruise nights, and barbecues.",
    public: true,
    fee: "$50/year",
    tags: ["muscle", "american", "drag"],
  },
  {
    id: "c4",
    name: "Miami Lowrider Society",
    members: 29,
    type: "Lowrider & Custom",
    location: "Little Havana, Miami",
    description: "Classic customs and lowriders. Culture, community, craftsmanship.",
    public: true,
    fee: "Free",
    tags: ["lowrider", "custom", "classic", "culture"],
  },
]

// Photo feed for each location — seed-stable picsum images
export const locationPhotos: Record<string, { id: string; url: string; user: string; car: string; likes: number; ago: string }[]> = {
  p1: [
    { id: "f1",  url: "https://picsum.photos/seed/w1/600/600",  user: "@carlosriv59",  car: "1994 Supra",          likes: 84,  ago: "2h"    },
    { id: "f2",  url: "https://picsum.photos/seed/w2/600/600",  user: "@miamiturbo",   car: "2020 GT-R",           likes: 61,  ago: "5h"    },
    { id: "f3",  url: "https://picsum.photos/seed/w3/600/600",  user: "@305builds",    car: "Ferrari 488",         likes: 210, ago: "1d"    },
    { id: "f4",  url: "https://picsum.photos/seed/w4/600/600",  user: "@southbeachv8", car: "Camaro SS",           likes: 47,  ago: "1d"    },
    { id: "f5",  url: "https://picsum.photos/seed/w5/600/600",  user: "@jdmmiami",     car: "Honda S2000",         likes: 99,  ago: "2d"    },
    { id: "f6",  url: "https://picsum.photos/seed/w6/600/600",  user: "@brickellgt",   car: "McLaren 720S",        likes: 315, ago: "3d"    },
  ],
  p2: [
    { id: "f7",  url: "https://picsum.photos/seed/d1/600/600",  user: "@designdistrict","car": "Lamborghini Urus", likes: 188, ago: "3h"    },
    { id: "f8",  url: "https://picsum.photos/seed/d2/600/600",  user: "@miamiturbo",   car: "Porsche GT3",         likes: 143, ago: "8h"    },
    { id: "f9",  url: "https://picsum.photos/seed/d3/600/600",  user: "@305builds",    car: "BMW M4 Competition",  likes: 77,  ago: "1d"    },
    { id: "f10", url: "https://picsum.photos/seed/d4/600/600",  user: "@carlosriv59",  car: "Nissan 370Z",         likes: 55,  ago: "2d"    },
  ],
  p3: [
    { id: "f11", url: "https://picsum.photos/seed/m1/600/600",  user: "@coralwheels",  car: "Dodge Challenger",    likes: 39,  ago: "1d"    },
    { id: "f12", url: "https://picsum.photos/seed/m2/600/600",  user: "@jdmmiami",     car: "Mitsubishi Evo IX",   likes: 88,  ago: "2d"    },
    { id: "f13", url: "https://picsum.photos/seed/m3/600/600",  user: "@southbeachv8", car: "Ford Mustang GT500",  likes: 101, ago: "3d"    },
  ],
  p4: [
    { id: "f14", url: "https://picsum.photos/seed/b1/600/600",  user: "@brickellgt",   car: "Rolls Royce Ghost",   likes: 402, ago: "4h"    },
    { id: "f15", url: "https://picsum.photos/seed/b2/600/600",  user: "@305builds",    car: "Ferrari SF90",        likes: 510, ago: "6h"    },
    { id: "f16", url: "https://picsum.photos/seed/b3/600/600",  user: "@designdistrict","car":"Bentley Continental",likes: 287, ago: "12h"   },
    { id: "f17", url: "https://picsum.photos/seed/b4/600/600",  user: "@miamiturbo",   car: "Aston Martin DB11",   likes: 193, ago: "1d"    },
    { id: "f18", url: "https://picsum.photos/seed/b5/600/600",  user: "@carlosriv59",  car: "1994 Supra",          likes: 120, ago: "2d"    },
    { id: "f19", url: "https://picsum.photos/seed/b6/600/600",  user: "@jdmmiami",     car: "Acura NSX",           likes: 98,  ago: "3d"    },
  ],
  p5: [
    { id: "f20", url: "https://picsum.photos/seed/o1/600/600",  user: "@overtownraw",  car: "Honda Civic Type R",  likes: 44,  ago: "6h"    },
    { id: "f21", url: "https://picsum.photos/seed/o2/600/600",  user: "@305builds",    car: "Subaru WRX STI",      likes: 67,  ago: "1d"    },
    { id: "f22", url: "https://picsum.photos/seed/o3/600/600",  user: "@coralwheels",  car: "Toyota GR86",         likes: 52,  ago: "2d"    },
  ],
}

export const userProfile = {
  name: "Carlos Rivera",
  handle: "@carlosriv59",
  location: "Miami, FL",
  joined: "Jan 2026",
  points: 2840,
  rank: "Gear Head",
  eventsAttended: 12,
  photosUploaded: 34,
  following: 89,
  followers: 203,
  garage: [
    {
      id: "g1",
      year: 2020,
      make: "Nissan",
      model: "370Z",
      color: "Magnetic Black",
      mods: ["Stillen exhaust", "KW coilovers", "Work VS-XX wheels", "Nismo aero"],
      photos: 8,
    },
    {
      id: "g2",
      year: 1994,
      make: "Toyota",
      model: "Supra",
      color: "Super White",
      mods: ["2JZ-GTE swap", "Single turbo 600whp", "Volk TE37 wheels"],
      photos: 14,
    },
  ],
}
